server:
  port: 8030 # dev, prod; rsc, func, etc; type; num;
spring:
  datasource:
    url: jdbc:h2:mem:testdb #만약 다른곳에서 h2 싶다면 tcp모드로 바꾸기
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true  #data.sql을 스키마가 만들어진 다음에 실행하게해서 오류를 없앰
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #실행되는 sql 보여줌
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

eureka:
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:3489@localhost:8210/eureka/